version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name:
          command: |
            cd frontend
            npm install
            npm run build
            npm run start

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build backend
          command: |
            # Your code here
            #
            cd backend
            npm install
            npm run build
            npm run start
      #- save_cache:
      #    paths: [frontend/node_modules]
      #    key: frontend-build

workflows:
  default:
    jobs:
      - build-backend
      - build-frontend